export {default as Whatgpt3} from './whatGPT3/Whatgpt3.jsx'
export {default as Blog} from './blog/Blog.jsx'
export {default as Features} from './features/Features.jsx'
export {default as Header} from './header/Header.jsx'
export {default as Possibility} from './possibility/Possibility.jsx'
export {default as Footer} from './footer/Footer.jsx'